### ISSUE TITLE
Elements in user interface are in lower case

### ISSUE THREAD

**Issue by hartenthaler** [JesseWebDotCom/webtrees-theme-modern#27] opened 2023-07-05 15:59 UTC
There are several labels in lowercase when using the "modern" theme.

See "gemeiname notiz" (it should be "Gemeinsame Notiz"):

![Screenshot (7)](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/6324175/bf8f5418-9e74-4dea-a129-22568c5ce289)

**Comment by JesseWebDotCom** [comment] 2023-07-05 23:14
by design as webtrees was not consistent with their casing. if you have something that is not lowercase, let me know of the class so I can include it.
```
/* standardize all labels since some come capitalized, others come all uppercase */
.wt-fact-label.ut {
    text-transform: lowercase;
    }
```

**Comment by JesseWebDotCom** [comment] 2023-07-07 13:52
closing, this is by design

**Closed by JesseWebDotCom** 2023-07-07 13:52 UTC

**Comment by hartenthaler** [comment] 2023-07-07 17:16
Oh! For German it is wrong, for English it is maybe "by design".

> webtrees was not consistent with their casing

Can you give me an example? I tried to find one, but was not successful. In my opinion: Don't correct the symptoms, get to the root of the problem. Your design makes it more bad. If a term is written wrong in webtrees it should be corrected. If you point me to the right direction, I will take care for that.

There are many more wrong labels now like "quellenzitat". This word exist only with a capital "Q" at the beginning.
![Screenshot (361)](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/6324175/eac9c587-d667-4d0f-be37-3bd4b0dc4c92)
