### ISSUE TITLE
Translation issue with 'you'

### ISSUE THREAD

**Issue by TheDutchJewel** [JesseWebDotCom/webtrees-theme-modern#30] opened 2023-07-07 05:48 UTC
There is a problem with the new string `you` in the `Facts and events` tab when using a non-English translation.

If you select yourself in the family tree, the English translation shows `you`, which is correct:
![en](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/46184729/8ddd4690-f338-4266-8d20-b14280a424d6)

But in Dutch I see `je hijzelf` instead of `jij`:
![nl](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/46184729/e9193b19-ece5-4cb1-8363-6e9d03689e53)

and in German `dein er selbst` instead of `du`:
![du](https://github.com/JesseWebDotCom/webtrees-theme-modern/assets/46184729/f48e1c59-98ae-430f-a9d1-f36d16e7fe44)

**Comment by JesseWebDotCom** [comment] 2023-07-07 05:55
Thanks - I leased in what you’re seeing, I know what the issue is and how to fix

**Comment by JesseWebDotCom** [comment] 2023-07-07 08:11
Try this: https://github.com/JesseWebDotCom/webtrees-theme-modern/releases/tag/0.1.0

**Comment by TheDutchJewel** [comment] 2023-07-07 09:30
The new version also does not work correctly when using a non-English translation.

In Dutch I see `jouw hijzelf` which should be `jij`.

And in German I see `dein er selbst` which should be `du`.

**Comment by JesseWebDotCom** [comment] 2023-07-07 13:50
Try the same 0.1.0 release again (I just fixed it)

**Comment by TheDutchJewel** [comment] 2023-07-07 16:02
Working fine now. Thank you!

**Comment by TheDutchJewel** [comment] 2023-07-07 16:14
I updated the Dutch translation. See [pull request#32](https://github.com/JesseWebDotCom/webtrees-theme-modern/pull/32).

**Comment by TheDutchJewel** [comment] 2023-07-08 11:30
Every version is released with 'your' ='jouw' instead of 'je', so I have to update it again.

 See [pull request #39](https://github.com/JesseWebDotCom/webtrees-theme-modern/pull/39).

**Comment by JesseWebDotCom** [comment] 2023-07-08 15:24
merged

**Closed by JesseWebDotCom** 2023-07-08 15:24 UTC
